apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: shipanything
  labels:
    app: rabbitmq
spec:
  replicas: 1
  image: rabbitmq:3.12-management-alpine
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  rabbitmq:
    additionalConfig: |
      default_user = admin
      default_pass = password
      management.tcp.port = 15672
      listeners.tcp.default = 5672
      disk_free_limit.absolute = 1GB
      vm_memory_high_watermark.absolute = 256MB
    additionalPlugins:
      - rabbitmq_management
      - rabbitmq_prometheus
      - rabbitmq_shovel
      - rabbitmq_shovel_management
  persistence:
    storageClassName: standard
    storage: 2Gi
  service:
    type: ClusterIP
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
            - name: rabbitmq
              env:
              - name: RABBITMQ_DEFAULT_USER
                value: "admin"
              - name: RABBITMQ_DEFAULT_PASS
                value: "password"
              - name: RABBITMQ_ERLANG_COOKIE
                value: "shipanything-rabbitmq-cookie"
              ports:
              - containerPort: 5672
                name: amqp
                protocol: TCP
              - containerPort: 15672
                name: management
                protocol: TCP
              - containerPort: 15692
                name: prometheus
                protocol: TCP
---
# Additional Service for management interface
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  namespace: shipanything
  labels:
    app: rabbitmq
spec:
  selector:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: rabbitmq
  ports:
  - name: management
    port: 15672
    targetPort: 15672
  - name: prometheus
    port: 15692
    targetPort: 15692
